### ISSUE TITLE
server test EADDRINUSE error

### ISSUE THREAD

**Issue by bariscc** [Kommunity-app/kommunity-backend#85]
Encountered below error on test while trying to submit pr:
```
 FAIL  test/unit/server.test.js
  ✕ server returns 404 (48ms)
  ✓ server returns 401 (26ms)
  ✓ server - /health returns OK (4ms)

  ● server returns 404

    listen EADDRINUSE :::4000

      218 |     }
      219 | 
    > 220 |     express.listen({ port: this.config.gqlServer.port }, () => {
          |             ^
      221 |       // eslint-disable-next-line no-new
      222 |       new SubscriptionServer({
      223 |         execute,

      at Function.listen (node_modules/express/lib/application.js:618:24)
      at App.listen [as initGqlServer] (src/lib/app.js:220:13)
      at App.initGqlServer [as initExpressApp] (src/lib/app.js:131:10)
      at App.initExpressApp [as init] (src/lib/app.js:51:10)
      at new init (src/lib/app.js:46:10)

  console.log src/lib/app.js:80
    EXPRESS 🎢  Server is ready at http://localhost:4008

GET /unknown-route 404 6.758 ms - 23
GET /api/v1/member/me 401 9.263 ms - -
GET /health 200 0.573 ms - -
```

I have checked, the address is not in use prior to running the test.
I changed the case order and found out it always the first case which is failing. routes are working ok.

Is this reproducable on your side? If not, any ideas?

**Comment by trkaplan** [comment]
Make sure, there are no changes in your project. (Stash all of your changes)
Then check port usage by using this command in terminal:
```bash
netstat -anv | egrep -w [.]4000.*LISTEN
```
If it returns a line, kill the process by running this:
`kill -9 <PID>`
*Replace **\<PID>** with the number, at the end of the line you received.

I don't get an error:
```bash
Found 0 errors
 PASS  test/unit/server.test.js
  ✓ server returns 404 (81ms)
  ✓ server returns 401 (18ms)
  ✓ server - /health returns OK (9ms)

  console.log src/lib/app.js:229
    GRAPHQL 🚀  Server ready at http://localhost:4000/gql

  console.log src/lib/app.js:230
    GRAPHQL ✨  Playground server ready at http://localhost:4000/gql-dev

  console.log src/lib/app.js:79
    EXPRESS 🎢  Server is ready at http://localhost:4008

GET /unknown-route 404 6.127 ms - 23
GET /api/v1/member/me 401 10.615 ms - -
GET /health 200 0.792 ms - -
```

**Comment by bariscc** [comment]
Must be one of my local changes caused this, I no longer receive an error after stashing the changes. Perhaps restarting the system did me a favor. closing this, thanks

**Comment by bariscc** [comment]
turns out docker-compose wasn't closing properly on quit. If anyone encounters similar error. using `docker-compose stop` properly shuts down the stalled processes.
